Description: >
  Capstone project for Cloud DevOps Engineering Nanodegree
  Author - Taha Azab
  Creating the EKS cluster.

Parameters:
  EnvironmentName:
    Description: An Environment name that will be prefixed to resources
    Type: String

Resources:
  EKSClusterInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - eks.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      RoleName: !Join ["-", [!Ref "EnvironmentName", "EKS-Cluster-Role"]]
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
        - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess

  ClusterInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
        - !Ref EKSClusterInstanceRole

  EKSCluster:
    Type: "AWS::EKS::Cluster"
    Properties:
      Version: 1.16
      Name: !Join ["", [!Ref "EnvironmentName", "-Cluster"]]
      RoleArn: !GetAtt EKSClusterInstanceRole.Arn
      ResourcesVpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue: !Sub "${EnvironmentName}-SCG"
        SubnetIds:
          Fn::Split: 
            - ","
            - Fn::ImportValue: !Sub "${EnvironmentName}-SUBNETS"

Outputs:
  EKSClusterId:
    Description: The Kubernetes Cluster Id.
    Value: !Ref EKSCluster
    Export:
      Name: !Sub "${EnvironmentName}-Cluster"
  EKSRoleArn:
    Description: The role that Amazon EKS will use to create AWS resources for Kubernetes clusters
    Value: !GetAtt EKSClusterInstanceRole.Arn
    Export:
      Name: !Sub "${EnvironmentName}-EKSRoleArn"
