apiVersion: v1
kind: Service
metadata:
  name: capstone-app
  labels:
    app: capstone-app
spec:
  type: LoadBalancer
  selector:
    app: capstone-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
      protocol: TCP